# .github/workflows/scheduled-readme-update.yml
name: Trigger Site to Update Github profile Readme.md

on:
  schedule:
    # Runs "at every 3 minutes" (see https://crontab.guru)
    - cron: '*/3 * * * *'
jobs:
  build:
    name: Trigger Readme Update
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to trigger update the image
        run: curl -X GET -d {} https://now-playing.experimentsofindrajith.in/updateCurrentlyPlaying